# Generated by Django 3.1.5 on 2021-02-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(default='Special', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('pdesc', models.CharField(default='delicious', max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pimage', models.ImageField(upload_to='menu_images/')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('category', models.ManyToManyField(related_name='cat_items', to='Restaurant1.Category')),
            ],
        ),
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant_name', models.CharField(default=None, max_length=50)),
                ('Restaurant_photo', models.ImageField(upload_to='restaurant_images/')),
                ('status', models.BooleanField(default=False)),
                ('password', models.CharField(default=None, max_length=30)),
                ('uname', models.CharField(default=None, max_length=30)),
                ('email', models.CharField(default=None, max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('items', models.ManyToManyField(blank=True, related_name='order', to='Restaurant1.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='rdata',
            field=models.ManyToManyField(related_name='rest_items', to='Restaurant1.restaurant'),
        ),
    ]
