# Generated by Django 3.1.5 on 2021-03-02 00:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='rdata',
        ),
        migrations.AddField(
            model_name='item',
            name='rname',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='special', max_length=50),
        ),
    ]
