# Generated by Django 3.1.5 on 2021-03-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant1', '0002_auto_20210302_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='rname',
        ),
        migrations.AddField(
            model_name='item',
            name='rdata',
            field=models.ManyToManyField(related_name='rest_items', to='Restaurant1.restaurant'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(related_name='cat_items', to='Restaurant1.Category'),
        ),
    ]
