# Generated by Django 3.1.5 on 2021-02-19 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderingOnline', '0003_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
