# Generated by Django 3.1.5 on 2021-03-13 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderingOnline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_no', models.CharField(default=None, max_length=12)),
                ('bank_password', models.CharField(default=None, max_length=12)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderingOnline.customer')),
            ],
        ),
    ]
