# Generated by Django 3.1.5 on 2021-03-21 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant1', '0023_auto_20210321_0743'),
        ('OrderingOnline', '0002_account_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Restaurant1.order_confirm')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderingOnline.customer')),
            ],
        ),
    ]
