# Generated by Django 3.1.5 on 2021-03-25 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderingOnline', '0004_auto_20210321_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.DecimalField(decimal_places=3, max_digits=5)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderingOnline.customer')),
            ],
        ),
    ]
