# Generated by Django 3.1.5 on 2021-03-25 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant1', '0025_auto_20210325_1346'),
        ('OrderingOnline', '0005_item_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_feedback',
            name='Item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Restaurant1.item'),
        ),
    ]
