# Generated by Django 3.1.5 on 2021-02-27 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0003_auto_20210224_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant_manager',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='restaurant_manager',
            name='user',
            field=models.OneToOneField(default='null', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurant_manager',
            name='Restaurant_name',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant_manager',
            name='Restaurant_photo',
            field=models.ImageField(upload_to='restaurant_images/'),
        ),
    ]
