# Generated by Django 3.1.5 on 2021-02-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20210227_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_manager',
            name='zipcode',
            field=models.CharField(default='null', max_length=6),
        ),
    ]
