# Generated by Django 3.1.5 on 2021-03-11 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OrderingOnline', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(default='Special', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('pdesc', models.CharField(default='delicious', max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pimage', models.ImageField(upload_to='menu_images/')),
                ('category', models.CharField(default='delicious', max_length=150)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('feedback', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
            ],
        ),
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant_name', models.CharField(default=None, max_length=50)),
                ('Restaurant_photo', models.ImageField(upload_to='restaurant_images/')),
                ('status', models.BooleanField(default=False)),
                ('password', models.CharField(default=None, max_length=30)),
                ('uname', models.CharField(default=None, max_length=30)),
                ('email', models.EmailField(default=None, max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='rdata',
            field=models.ManyToManyField(related_name='rest_items', to='Restaurant1.restaurant'),
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('Items_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant1.item')),
                ('userdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderingOnline.customer')),
            ],
        ),
    ]
