# Generated by Django 3.1.5 on 2021-03-11 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderingOnline', '__first__'),
        ('Restaurant1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='not_delivered', max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Items_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant1.item')),
                ('rdata', models.ManyToManyField(related_name='rest_order', to='Restaurant1.restaurant')),
                ('userdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderingOnline.customer')),
            ],
        ),
    ]
