# Generated by Django 3.1.5 on 2021-03-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant1', '0003_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='feedback',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=1),
        ),
    ]
