# Generated by Django 3.1.5 on 2021-03-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant1', '0003_auto_20210302_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='delicious', max_length=150),
        ),
    ]
