# Generated by Django 3.1.5 on 2021-03-07 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderingOnline', '__first__'),
        ('Restaurant1', '0004_auto_20210302_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='feedback',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='order_items_detail', to='Restaurant1.Item'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(default=None, max_length=50),
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('Items_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='Restaurant1.item')),
                ('userdata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_cart', to='OrderingOnline.customer')),
            ],
        ),
    ]
