# Generated by Django 3.1.5 on 2021-03-07 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderingOnline', '__first__'),
        ('Restaurant1', '0005_auto_20210307_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Items_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant1.item'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='userdata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderingOnline.customer'),
        ),
    ]
