# Generated by Django 3.1.5 on 2021-03-13 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant1', '0005_orderproduct_cartdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='Items_data',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='userdata',
        ),
    ]
