# Generated by Django 3.1.5 on 2021-03-13 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderingOnline', '0002_account_user'),
        ('Restaurant1', '0006_auto_20210314_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='userdata',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OrderingOnline.customer'),
            preserve_default=False,
        ),
    ]
