# Generated by Django 3.1.5 on 2021-03-13 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant1', '0007_orderproduct_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='rdata',
        ),
    ]
