# Generated by Django 3.1.5 on 2021-03-15 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant1', '0008_remove_orderproduct_rdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant1.item')),
            ],
        ),
    ]
