# Generated by Django 3.1.5 on 2021-03-15 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant1', '0009_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_confirm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant1.item')),
            ],
        ),
    ]
