# Generated by Django 3.1.5 on 2021-03-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant1', '0011_auto_20210316_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='final_amount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='item',
            name='total',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='order_confirm',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
