# Generated by Django 3.1.5 on 2021-03-17 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant1', '0017_order_confirm_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_confirm',
            name='creat_on',
            field=models.DateField(default=datetime.date(2021, 3, 18)),
        ),
        migrations.AddField(
            model_name='order_confirm',
            name='feedback',
            field=models.IntegerField(default=0),
        ),
    ]
