# Generated by Django 3.1.5 on 2021-03-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant1', '0019_auto_20210319_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=6, default=20, max_digits=10),
            preserve_default=False,
        ),
    ]
