# Generated by Django 3.1.5 on 2021-03-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant1', '0020_orderproduct_delivery_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_confirm',
            name='waiting_status',
            field=models.BooleanField(default=False),
        ),
    ]
