# Generated by Django 3.1.5 on 2021-03-18 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderingOnline', '0002_account_user'),
        ('Restaurant1', '0021_order_confirm_waiting_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='favourite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('final_amount', models.DecimalField(decimal_places=10, default=0, max_digits=19)),
                ('Items_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant1.item')),
                ('userdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderingOnline.customer')),
            ],
        ),
    ]
