# Generated by Django 3.1.5 on 2021-03-21 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant1', '0022_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=6, default=40.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order_confirm',
            name='creat_on',
            field=models.DateField(default=datetime.date(2021, 3, 21)),
        ),
    ]
