# Generated by Django 3.1.5 on 2021-03-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant1', '0023_auto_20210321_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='delivery_charge',
        ),
        migrations.AlterField(
            model_name='cart',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=6, default=40.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='cart',
            name='final_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='final_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='feedback',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='total',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
