# Generated by Django 3.1.5 on 2021-03-25 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant1', '0024_auto_20210321_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_confirm',
            name='creat_on',
            field=models.DateField(default=datetime.date(2021, 3, 25)),
        ),
    ]
