# Generated by Django 3.1.5 on 2021-03-25 13:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant1', '0025_auto_20210325_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 13, 16, 49, 838293, tzinfo=utc)),
        ),
    ]
