# Generated by Django 3.1.5 on 2021-03-25 13:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant1', '0026_auto_20210325_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_confirm',
            name='creat_on',
        ),
        migrations.AddField(
            model_name='order_confirm',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 3, 25, 13, 18, 16, 945136, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 13, 18, 16, 945136, tzinfo=utc)),
        ),
    ]
