# Generated by Django 3.1.5 on 2021-03-27 10:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant1', '0027_auto_20210325_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_confirm',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2021, 3, 27, 10, 3, 14, 366148, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 10, 3, 14, 366148, tzinfo=utc)),
        ),
    ]
