# Generated by Django 3.1.5 on 2021-02-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant_manager',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Restaurant_name', models.CharField(max_length=50)),
                ('Restaurant_photo', models.ImageField(upload_to='')),
                ('status', models.BooleanField(default=False)),
                ('uname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=6)),
            ],
        ),
    ]
