# Generated by Django 3.1.5 on 2021-03-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_boy', '0002_remove_deliveryboy_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='salary',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='status',
            field=models.BooleanField(default='Not_Availale'),
        ),
    ]
