# Generated by Django 3.1.5 on 2021-03-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_boy', '0003_auto_20210319_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboy',
            name='status',
            field=models.BooleanField(default='Available'),
        ),
    ]
