# Generated by Django 3.1.5 on 2021-03-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_boy', '0004_auto_20210319_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboy',
            name='status',
            field=models.CharField(default='Available', max_length=50),
        ),
    ]
